### ISSUE TITLE
zoom

### ISSUE THREAD

**Issue by HA-NA123** [micheleriva/vue-product-spinner#45]
there is no zoom option for each image.

**Comment by micheleriva** [comment]
Hi @HA-NA123 ,
do you have an example of what you'd like to achieve?

**Comment by HA-NA123** [comment]
yes i want when click on each image it will be zoom in. like this https://samueljon.es/vue-image-zoomer/

**Comment by micheleriva** [comment]
@HA-NA123 I took a look at the repo you've linked, and sadly I have to say that I am not currently considering adding this feature. While it could be technically easy to add it, it would increase by a lot the JS bundle's final size, and there could be people not wanting this feature. It wouldn't be a minor feature, so I'd prefer to keep it easy for the moment.

I'll leave the issue here with the "feature voting" label. If anyone else wants this feature, please let me know, and I'll consider it.

If you have a good idea for implementing it without increasing the bundle size by a lot, I'm open to PRs!
Have a nice day
